
INSERT INTO public.cirqueshow VALUES
--INSERT OVO
	(1, 'OVO', 'Itinerante', 'abc\\030',  
  	CAST(ARRAY [('Apertura', 'El emocionante y ajetreado mundo está representado por la música de samba y las luces brillantes, luego una 		calma repentina, las luces brillantes cambian a luz natural cálida y la samba pesada se convierte en una canción de guitarra calmante'),
	('Malabarismo de Pies y Juegos Icarianos','Un grupo de hormigas hacen malabares con kiwis, maíz, rebanadas de berenjena y otras		hormigas, todas en sus pies.'),
	('Balance de Mano', 'Una libélula solitaria se balancea precariamente en un bloque alto y giratorio.'),
	('Correas Aéreas', 'Las artistas vuelan sobre la audiencia suspendidas de cuerdas que cuelgan de un transportador con un elemento 		rotativo sobre sus cabezas. Es un vuelo en cuatro dimensiones que exige precisión además de las habilidades y la fuerza física 		necesarias para moverse a alta velocidad en 360 grados.'),
	('Diábolo', 'Una luciérnaga manipula y lanza múltiples diabolos a la vez.'),
	('Creatura', 'Parte sinuosa, parte insecto, la Criatura danza en un tema que es todo suyo, el se curva, tuerce en nudos sus 		miembros elásticos en constante movimiento.'),
	('Marco Aéreo', 'Un hombre fuerte y una muñeca con cara de porcelana que despiertan por una descarga eléctrica emergen de su caja 		musical y cobran vida. Los dos artistas escalan a la cima del aparado de 4 metros de altura. En un número basado en la confianza mutua, 	el atrapador se convierte en un trapecio humano y lanza a su compañera en el aire donde realiza saltos mortales cada vez más intrincados.'),
	('Contorsión', 'Una araña usa la misma cuerda vertical que las mariposas para crear múltiples posturas flexibles, mientras que otra en el suelo usa los apoyabrazos para mantener el equilibrio mientras la espalda y las piernas se retuercen en múltiples posiciones.'),
	('Trío Acrobático', 'dos artistas varones usan técnicas similares a las de la gimnasia acrobática (acrosport) para lanzar al aire a una mujer.'),
	('Slack Wire', 'En un cable suelto (y algunas veces en movimiento), una araña se balancea con sus piernas y manos, y en un punto monta un monociclo.'),
	('Piernas', 'Un baile único, múltiples piernas emergen a través de agujeros en el escenario.'),
	('Trampolín, Power Track y Muro', 'Los grillos rebotan en un trampolín largo en el suelo llamado una vía de poder, realizan giros a una velocidad asombrosa. Los grillos también utilizan un trampolín para saltar a la pared, en la pared el salto y aterrizar en el trampolín.'),
	('Banquete', 'El final del espectáculo.')] AS ACTO[]),
  	CAST(ARRAY [('DEBORAH', 'COLKE','DIRECTOR'),
	('GRINGO', 'CARDIA','ESCENARIO'),('BERNA','CEPPAS','COMPOSITOR'),('LIZ','VANDAL','VESTUARIO')] AS DatosExtra[]),
  	ARRAY [ 'Brisa Do Mar','Extranjero','Hormigas(juegos de malabares de pies y de Icarian)','Capullo (tejido)','Frevo Zumbido(Diabolos)','Orvalho (balanceo de manos)','Carimbo da Creatura(Creatura)','Dueto de amor(Correas Duo)','Scarabee','Cuna rusa','Sexy Web','Piernas','Chicas de pulgas','Acro trio','Superhéroe (Slackwire)','Secret Samba Luv','Parede (Muro)','Banquete (Banquete y Arcos)'],
	'Ovo es una producción de circo itinerante del Cirque du Soleil que se estrenó en Montreal , Canadá , en 2009. La creadora y directora de Ovo , Deborah Colker , se inspiró en el mundo de los insectos . La idea para Ovo no era ser sobre los actos, ni el baile, ni los insectos, sino sobre el movimiento. El movimiento de la vida impregna todo el espectáculo con criaturas que vuelan, saltan, saltan y se arrastran. La compositora Berna Ceppas le dio vida adicional a Ovo con una música inspirada en la música de Brasil . Ovo significa "huevo" en portugués y representa el hilo subyacente a través del show. Gráficamente, dentro del logo de Ovo , hay un insecto. Las dos O representan los ojos y la V forma la nariz y las antenas.', null),
--INSERT AMALUNA
	(2, 'Amaluna', 'Itinerante', 'abc\\030',  
  	CAST(ARRAY [('Concurso de Magia', 'La diosa Prospera reúne a todas las personas de la isla para celebrar el viaje de su hija Miranda hacia la condición de mujer a través de esta secuencia de baile de apertura'),
	('Uniciclo','Dos artistas realizarían trucos en pequeños monociclos juntos, lanzándose entre ellos y con los monociclos.'),
	('Correas Aéreas', 'La diosa de la tormenta se eleva sobre el escenario y la audiencia en un acto en solitario mientras Prospera evoca una tormenta que trae a un grupo de hombres a la isla, incluido Romeo, el nuevo amor de Miranda.'),
	('Danza del Pavo Real', 'La diosa del pavo real se encuentra con Romeo en el bosque y realiza una danza suave pero inquietante que simboliza la pureza del amor.'),
	('Payasos', 'Mainha, la niñera de la infancia de Miranda, y Papulya, la sirvienta de Romeo, se enamoran durante todo el espectáculo.'),
	('Cerceau y Waterbowl', 'La diosa de la luna se le aparece a Miranda montando un Cerceau, otorgándole su bendición con una canción inquietante. Romeo observa a Miranda mientras juega en la cuba de agua, descubriendo su propia fisicalidad y expresando su sinuosa sexualidad mientras realiza una desafiante rutina de equilibrio de manos antes de bucear y serpentear a través del agua.'),
	('Barras Desiguales', 'Las amazonas, los feroces guerreros de la isla, muestran sus habilidades al voltear y saltar entre cuatro barras de altura irregular.'),
	('Teeterboard', 'Los hombres han sido capturados y usan un Teeterboard para impulsarse hacia arriba, escapando de la gravedad y de su prisión.'),
	('Diosa del Equilibrio', 'La diosa del equilibrio emerge y equilibra frondas de palmeras de varios tamaños una sobre la otra, antes de retirar el palo más pequeño y todo se derrumba. Esto representa la delicadeza del equilibrio y la confianza en una relación.'),
	('1000 Brazos y Palos', 'Durante esta secuencia de transición / baile, una línea de artistas se mueve en sincronía pero a intervalos ligeramente diferentes para crear el efecto de las plumas de pavo real.'),
	('Polo Chino', 'Romeo realiza hazañas de fuerza para impresionar a Miranda en un solo palo vertical mientras otros hombres bailan alrededor de la base con palos de bambú.'),
	('Malabares', 'En Cali, la lagartija mascota de Miranda se despoja de su piel y realizó un increíble acto de malabarismo con pelotas que a veces están en llamas, todo sobre el tazón de agua.'),
	('Banquine', 'Una tradición acrobática italiana que se remonta a la Edad Media que combina gimnasia y ballet. Exhibiendo la agilidad del cuerpo humano. Los artistas realizan una secuencia de hazañas y pirámides humanas con sus movimientos perfectamente sincronizados.')] AS ACTO[]),
  	CAST(ARRAY [('DIANE', 'PAULUS','DIRECTOR'),
	('SCOTT PASK', 'CARDIA','ESCENARIO'),('GUY','DUBUC','COMPOSITOR'),('MÉRÉDITH','CARON','VESTUARIO')] AS DatosExtra[]),
  	ARRAY [ 'Todos vienen juntos','Tempest ','Reunión encantada','Canción de Barras Desiguales','Esperanza','O Ma Ley','Burn Me Up ','Susurro','Ena Fee Alyne','Criatura de la luz ','Mutaciones','Run','Sexy Web','Piernas','Chicas de pulgas','Acro trio','Superhéroe (Slackwire)','Secret Samba Luv','Parede (Muro)','Banquete (Banquete y Arcos)'],
	'Amaluna es un espectáculo itinerante del Cirque du Soleil , creado y dirigido por Diane Paulus . Se estrenó en Montreal , Quebec, Canadá, el 19 de abril de 2012. Inspirado libremente por William Shakespeare s The Tempest ,la historia tiene lugar en una isla gobernada por diosas. Durante una tormenta, un grupo de hombres son arrastrados a la orilla. La hija de la reina se enamora de uno de los jóvenes, y las pruebas de su amor son la base de la narrativa principal del programa. El programa es notable por tener un reparto que es 70% femenino.', 
	null),
--INSERT ALEGRÍA
	(3, 'Alegría', 'Itinerante', 'abc\\030',  
  	CAST(ARRAY [('Trapecio Sincronizado', 'Sentados en sus trapecios individuales, dos aerialistas ejecutan en una demostración de armonía y belleza. En esta rutina, el atrevido dúo desafía la ley de la gravedad con sus torsiones y maniobras en el aire, aumentando cada vez más las hazañas acrobáticas.'),
	('Payasos','Los payasos demuestran una danza muy alegre.'),
	('Powertrack', 'Los Bronx son los jóvenes y los duros; son la generación por venir. Individualmente así como pandilla, sus hazañas acrobáticas en el circuito rápido son la medida de su poder. Son fuertes, aunque también sensuales y elegantes. Son una fuerza imponente a la vez que una celebración de la juventud.'),
	('Malabarismo', 'Combinando agilidad, fortaleza y elegancia, el artista solista eleva su cuerpo por el aire habilidosamente, equilibrando su peso sobre una mano y luego sobre la otra mientras crea elegantes y notables figuras.'),
	('Baile con Cuchillo y Fuego', 'Tribal y mágico, este auténtico baile ritual es ejecutado al ritmo de tambores de congo de un artista serpenteando sus cuchillos de fuego como batuta por su cuerpo entero, desde sus pies hasta sus manos y boca en una danza seductora y peligrosa.'),
	('Payaso con Vela', 'Un payaso con vela baila alegremente.'),
	('Manipulación', ' Consiste en la manipulación de aros hula, cintas, tiras, etc.'),
	('Tormenta de Nieve', 'Reflejando el eterno espíritu de la humanidad, que da a ver las emociones de la vida en el corazón; los payasos son los testigos del paso de los siglos, siendo los comentadores sociales del mundo de Alegría. Basados en la vida real, relatan historias de la vida cotidiana donde todos son héroes y donde cualquiera puede enamorarse y tener el corazón roto. Los payasos son los visionarios, filósofos de lo absurdo. Atractivos, cómicos y pueriles, convierten al mundo en un circo.'),
	('Hombre Volador', ' Este virtuoso desafía la gravedad combinando la elasticidad del bungee y el poder de los aros de gimnasia, el artista se lanza a través del aire mientras ejecuta proezas acrobáticas. Su impresionante presentación es una amalgama de increíble habilidad, agilidad y fortaleza. Aunque su esculpido físico es imponente, es delicado y grácil.'),
	('Barras Rusas', 'Acróbatas voladores son empujados en el aire por una sola, doble o triple barra que se alza sobre los hombros robustos de los captores poderosos. Los acróbatas realizan saltos sincronizados a una velocidad increíble. Las Barras Rusas requieren una gran cantidad de concentración y la confianza mutua entre los artistas intérpretes o ejecutantes. Cada barra es flexible y mide de dos a seis pulgadas de ancho.'),
	('Contorsión', 'Estas dos criaturas semejantes a un ave ejecutan imaginativas e impresionantes hazañas de flexibilidad y equilibrio mientras se alzan sobre una mesa giratoria aparentemente ingrávida. Con sus movimientos fluidos, el dúo se mueve como una sola entidad, metamorfoseándose en formas esculpidas de manera extraordinaria.'),
	('Área de Barra Alta', 'Tres barras a una altura de más de 40 pies sobre el escenario forman el parque aéreo de acróbatas atrevidos que vuelan hacia los brazos de los captores poderosos, suspendidos de sus rodillas sobre un columpio humano. El acto, realizado por acróbatas rusos, culmina en un desafío a la muerte, saltando todo desde arriba a la red.')] AS ACTO[]),
  	CAST(ARRAY [('FRANCO', 'DRAGONE','DIRECTOR'),
	('MICHEL', 'CRETE','ESCENARIO'),('RENÉ','DUPÉRÉ','COMPOSITOR'),('DOMINIQUE','LEMIEUX','VESTUARIO')] AS DatosExtra[]),
  	ARRAY [ 'Alegría (Final)','Vai Vedrai (Trapecio Sincronizado)','Kalandéro','Querer (Instalación de Barra Alta)','Irna (Power Track)','Taruka (Contorsionismo)','Jeux Denfants (Intermedio)','Mirko (Apertura)','Icare (Barra Alta)','Ibis','Valsapena(Power Track)','Nocturne (Tormenta de Nieve)','Cerceaux (Manipulación/Aros)','Malioumba (Hombre Volador)'],
	'Alegría fue el show más popular y más querido por todo el público del Cirque du Soleil. Desde su estreno en abril de 1994, se ha presentado más de 7.000 veces y visto por más de 14 millones de espectadores en más de 250 ciudades alrededor del mundo. Alegría se originó para ser un espectáculo superior con gira en carpa. Sin embargo, Alegría tomó un breve respiro y pasó a ser un show residente en la MGM Beau Rivage casino desde mayo de 1999 a octubre de 2000, año en el que retomó su gira mundial en carpa. Comenzando con su tour 2009 - 2010 América del Norte, el show fue convertido en formato de arena (sin carpa), que le permitió visitar ciudades que antes eran inaccesibles para el tour debido a su gran carpa. Realizó su última función el 29 de diciembre de 2018 en Ambéres (Bélgica).', 
	null),
--INSERT KURIOS
	(4, 'Kurios', 'Itinerante', 'abc\\030',  
  	CAST(ARRAY [('Chaos Synchro 1900 (Juggling / Drums)', 'Un malabarista, percusionistas y bailarines realizan una fusión de acrobacias, excéntricos, acróbatas.'),
	('Russian Cradle Duo','Un catcher arroja a su compañero al aire, donde ella realiza saltos más y más intrincados.'),
	('Bicicleta aérea', 'Una mujer monta una bicicleta que despega al aire y realiza varios trucos parecidos a un trapecio.'),
	('The Invisible Circus', 'Nunca has visto algo así ... ¡y nunca lo harás!.'),
	('Contorsión', 'Los cuatro artistas que se retuercen ejecutan una serie de pirámides y figuras utilizando la Mano Mecánica como plataforma.'),
	('Mundo al revés (Balanceo de manos sobre sillas) ', 'Un rendimiento al revés y un lado derecho hacia arriba con dos acróbatas que hacen balance en una serie de sillas.'),
	('Rola Bola', 'Un aviador se balancea en tubos en una plataforma suspendida en el aire.'),
	('Acro Net', 'Los artistas saltan al aire utilizando una amplia red. Son atrapados y volteados en el aire.'),
	('Ley Cómica', 'Un hombre trae a una mujer de la audiencia y la invita a subir a su mundo.'),
	('Correas aéreas', 'Los "gemelos siameses" que cuelgan en el aire de las correas se separan cuando vuelan por encima del escenario en una serie de figuras acrobáticas, a veces como pareja, a veces en solitario.'),
	('YoYos', 'El dos veces campeón mundial de YoYo NEGRO realiza un acto con YoYos como un personaje "Maestro de la época".'),
	('Teatro de las manos', 'Los artistas presentan una historia de una persona que salta, salta y luego se enamora, usando sus manos como muñecos vestidos con sombreros y zapatos en miniatura.'),
	('Banquine', 'Un grupo de artistas realiza secuencias espectaculares de acrobacias sincronizadas y pirámides humanas.')] AS ACTO[]),
  	CAST(ARRAY [('MICHEL', 'LAPRISE','DIRECTOR'),
	('STÉPHANE', 'ROY','ESCENARIO'),('RAPHAEL','BEAU','COMPOSITOR'),('PHILLIPPE','GUILLOTEL','VESTUARIO')] AS DatosExtra[]),
  	ARRAY [ '11h11 (Apertura)','Telegrama Steampunk (Bicicleta Aérea)','Bella Donna Twist (Chaos Synchro 1900)','Gravedad levitas (cuna rusa)','Monde inversé (mundo al revés)','Hypnotique (Contorción)','Salida (Teatro de manos / Transición a Rola Bola)','Vuelo temible (Rola Bola)','Nubes (Acro Net)','Créature de siam (Aerial Straps Duo)','Wat U No Wen (Banquine)','Usted debe estar bromeando (final)'],
	'Kurios es unaproducción itinerante del Cirque du Soleil que se estrenó el 24 de abril de 2014 en Montreal, Quebec , Canadá, bajo el título completo de Kurios: Gabinete de Curiosidades . Creado y dirigido por Michel Laprise, mira a un inventor mundial de finales del siglo XIX que inventa una máquina que desafía las leyes del tiempo, el espacio y la dimensión para reinventar todo a su alrededor conelementos steampunk con personajes de otra dimensión. Que interactúan con él y un homenaje al poder de la imaginación humana.', null);

INSERT INTO public.personaje VALUES
--INSERT PERSONAJES DE OVO
	(1,'Maestro Flipo','El personaje principal, Master Flipo, mantiene todo en orden en este mundo caótico.',1),
	(2,'La Mariquita','Es la tercera directora que trae vida y alegría al mundo de los insectos, y también termina enamorándose del extranjero.',1),
	(3,'El Extranjero','El extranjero, otro personaje principal, es una mosca de una tierra lejana que trae consigo el misterioso ovo.',1),
	(4,'La Libélula','La libélula revolotea a lo largo de toda la actuación y realiza el acto de equilibrio de la mano.',1),
	(5,'Arañas','Cuatro arañas proporcionan misterio y precaución a lo largo del espectáculo.',1),
	(6,'Pulgas','Tres pulgones saltan con destellos de rojo y amarillo mientras realizan acro-trío.',1),
	(7,'Hormigas','Las hormigas llevan kiwi y maíz con ellos en su viaje mientras realizan malabares con el pie.',1)
	(8,'Mariposas','El dúo las mariposas vuelan por el aire.',1),
	(9,'La Luciérnaga','La luciérnaga revolotea acerca de actuar con diabolos.',1),
	(10,'El Mosquito','El mosquito agrega carácter a la actuación al tiempo que forma parte del powertrack, el trampolín y el acto de pared.',1),
	(11,'Escarabajos','Los escarabajos fuertes vuelan por el aire girando y girando.',1),
	(12,'Grillos','Los 10 grillos saltan y saltan en rayas verdes como lo hacen la pista de aire, el trampolín y la pared.',1),
	(13,'Creatura','Una misteriosa creatura le da vida a la fiesta con su baile.',1),
	(14,'Cucarachas','Las 9 cucarachas se ven cantando y tocando música durante toda la actuación.',1),
--INSERT PERSONAJES DE AMALUNA
	(15,'Próspera','Próspera es una chamán con poderes mágicos, pero ella está muy impulsada por emociones humanas. El bienestar de su hija es su preocupación más importante. Ella sabe que debe dejar que Miranda encuentre el amor y que haga su propio camino en el mundo, pero ella puede usar sus poderes para influir en la forma en que esto se produce, y ella siempre será una fuerza de protección en la vida de su hija.',2),
	(16,'Miranda','Miranda es una chica a punto de ser mujer. Ella es una romántica, llena de diversión, entusiasmo, sueños y travesuras, que se deleita en el mundo estimulante de Amaluna con todas sus ricas tradiciones, la cultura y la espléndida flora y fauna.',2),
	(17,'Romeo','Prospera evoca la tormenta que conduce a la llegada de un grupo de hombres jóvenes, y ella influye en los eventos que llevan a su líder, el príncipe apuesto Romeo, y Miranda juntos. Él es tan hambriento de amor verdadero, pero él todavía no sabe lo difícil que el camino por delante será.',2),
	(18,'Cali','La mitad lagarto, mitad humano, celoso, Cali ha conocido Miranda toda su vida y aunque ella piensa en él sólo como una mascota, él está enamorado de ella. Y está decidido a evitar que Romeo gane a Miranda primero.',2),
	(19,'Jeeves','Jeeves criado de Romeo llega con los jóvenes y rápidamente se enamora de Deeda, enfermera de la infancia de Miranda.',2),
	(20,'Deeva','Criada de Miranda quién se enamora de Jeeves y juntos forman una familia.',2),
	(21,'Diosas y Amazonas','La Diosa del Pavo Real, La Diosa de la Luna, La Diosa del Balance, Las Valquirias y Las Amazonas son una fuerte presencia femenina en Amaluna. Ellas usan sus poderes para ayudar a veces y a veces para obstaculizar a los jóvenes amantes en su búsqueda de la felicidad',2),
--INSERT PERSONAJES DE ALEGRÍA
	(22,'El Fleur','En ausencia de un rey, las Nostálgicas Aves Viejas tienen una sola opción a seguir: el Fleur. El Fleur es nuestro patrón dentro del mundo de Alegría; él es un poco impredecible y un hombre peligroso quien se cree el rey gobernante de Alegría. Fleur, nuestro guía en el mundo de Alegría, es poco fiable, espectral e imprevisible. Con su cetro de luz se pavonea de un sitio a otro siguiendo la corriente a las presuntuosas aves viejas que lo rodean. Puede parecer divertido y animado, pero es narigudo y jorobado. Fleur es en realidad celoso, mezquino e irascible. Es un personaje corrupto hasta la médula pero va ataviado con una vistosa chaqueta de cochero de terciopelo rojo, un sombrero negro y un chaleco de pedrería que apenas logra cubrir la grotesca protuberancia de su barriga.',3),
	(23,'Las Nostálgicas Aves Viejas','Las Nostálgicas Aves Viejas han vivido en el lugar por mucho tiempo desde su existencia. Cortesanas sin una corte, las Aves Viejas admiran sus reflejos en los marcos de los espejos, pero ellas son solo unas conchas vacías, sombras de su propio ser. Las Aves Viejas observan lo que acontece como si siguiesen siendo jóvenes y hermosas, y el mundo aún les perteneciera. Son la vieja aristocracia, convencida pese a todo de su poder y hermosura. Pero en realidad son retorcidas, deformes y feas. Visten con sombreros originales y se esconden en sus atuendos exuberantes de profundos tonos malvas, verdes y dorados, recubiertos de encaje, joyas y bordados.',3),
	(24,'Tamir y pequeño Tamir','El Tamir aparece cuando lo considera necesario, solamente desaparece una vez ya cuando ha cumplido su misión. Su gran sonrisa y ojos son las ventanas de un alma generosa, siempre a mano y dispuesto a ayudar, es como una criatura mágica que aparece cuando se le necesita y vuelve a desaparecer en cuanto ha cumplido su misión. Vestido con su distintivo abrigo dorado, sus pantalones blancos acolchados y su sombrero bombín, sonríe de oreja a oreja y mira con ojos brillantes que son las ventanas de su alma generosa.',3),
	(25,'Las Ninfas','Mientras celebran cada aliento de vida, la exuberancia de lo sencillo, las frágiles ninfas son infecciosas, jóvenes y etéreas. Su volubilidad es contagiosa y su encantadora danza es capaz de ablandar un corazón de piedra. Estas amables criaturas se deslizan por el escenario cargadas de sensualidad y belleza.',3),
	(26,'Los Bronx','Los Bronx son jóvenes y duros. Ellos son la próxima generación, listos para derrocar al antiguo régimen y arrebatarles el poder a los débiles Aves Viejas.',3),
	(27,'Los Ángeles','Los Ángeles blancos son los elegantes guardianes de la Alegría. Ágiles, seguros de sí mismos y audaces, son la juventud del mañana que se ha posado en el palacio de los Cielos.',3),
	(28,'La Cantante de Blanco','La Cantante de Blanco es el símbolo de todo lo que alguna vez fue bueno en el antiguo régimen. Ella es la narradora de este mundo, cuyo canto refleja todo lo que ve. Canta su melancolía y su desesperación, su dicha y su felicidad. Su luminoso vestido blanco es exquisito: metros y metros de ondulante crinolina bajo un corset y un miriñaque adornados con gemas y perlas. Con ese vestido y sus largos guantes blancos, sus movimientos recuerdan a los de la muñeca de porcelana de un joyero.',3),
	(29,'La Cantante de Negro',' La Cantante de Negro es el alter-ego de la Cantante de Blanco. Aunque también expresa en canciones el ambiente de Alegría, hay maldad en ella, transpira una cierta maldad. Su elegante vestido negro, que es un reflejo del de la Cantante de Blanco, esconde los secretos de su alma atormentada. También esconde muchos secretos en su oscuro corazón.',3),
	(30,'Los Payasos','Los payasos han sido capaces de resistir cambios en la política y transformaciones sociales. Testigos de los siglos que pasan, son los comentadores sociales de la Alegría. Los payasos reflejan el espíritu eterno de la humanidad, son visionarios, filósofos del absurdo. Son entrañables, cómicos e infantiles y convierten el mundo entero en su circo. Tienen los pies en el suelo, son realistas y narran pequeñas historias de la vida cotidiana, en las que todos somos héroes, todos podemos enamorarnos y a todos nos pueden romper el corazón.',3),
--INSERT PERSONAJES DE KURIOS
	(31,'El Buscador','Un científico, está en una búsqueda en la que crea una máquina para viajar a otra dimensión para encontrar el lugar donde se encuentran lo posible y lo imposible.',4),
	(32,'Nico el hombre de acordeón','El traje de acordeón de Nico le permite agacharse o ponerse de pie para que pueda estar al nivel de la vista con absolutamente todo el mundo.',4),
	(33,'Sr. Microcosmos','Una figura de autoridad, el Sr. Microcosmos es el líder del grupo. Este capítulo serio es la encarnación del progreso tecnológico.',4),
	(34,'Klara, el telégrafo de lo invisible','Klara puede recibir ondas alfa girando sobre sus talones y apuntando su falda de aro en varias direcciones.',4),
	(35,'Mini Lili','Ella representa la mente inconsciente del Sr. Microcosmos, su yo intuitivo, su lado frágil y poético.',4),
	(36,'Jean-Claude','Gemelos unidos que son la encarnación de la unidad y la separación.',4),
	(37,'The Kurios','El Buscador se rodea de una brigada de asistentes, entre ellos el Winch Kurios y la Succión Cup Kurios.',4)
	(38,'Los curiosianos','Son los habitantes de un país imaginario llamado Curiosistán y aparecen en el mundo del Buscador para encender su imaginación.',4);

