CALL copiar_aspiratne_artista(1,null);
CALL copiar_aspiratne_artista(2,null);
CALL copiar_aspiratne_artista(3,null);
CALL copiar_aspiratne_artista(4,'The Incredible');
CALL copiar_aspiratne_artista(5,'The Incredible');
CALL copiar_aspiratne_artista(6,'The Incredible');
CALL copiar_aspiratne_artista(7,'The Incredible');
CALL copiar_aspiratne_artista(8,'The Incredible');
CALL copiar_aspiratne_artista(9,'The Incredible');
CALL copiar_aspiratne_artista(10,'The Incredible');
CALL copiar_aspiratne_artista(11,'The Incredible');
CALL copiar_aspiratne_artista(12,'The Incredible');
CALL copiar_aspiratne_artista(13,'The Incredible');
CALL copiar_aspiratne_artista(14,'The Incredible');
CALL copiar_aspiratne_artista(15,'The Incredible');
CALL copiar_aspiratne_artista(16,'The Incredible');
CALL copiar_aspiratne_artista(17,'The Incredible');
CALL copiar_aspiratne_artista(18,'The Incredible');
CALL copiar_aspiratne_artista(19,'The Incredible');
CALL copiar_aspiratne_artista(20,'The Incredible');
CALL copiar_aspiratne_artista(21,'The Incredible');
CALL copiar_aspiratne_artista(22,'The Incredible');
CALL copiar_aspiratne_artista(23,'The Incredible');
CALL copiar_aspiratne_artista(24,'The Incredible');
CALL copiar_aspiratne_artista(25,'The Incredible');
CALL copiar_aspiratne_artista(26,'The Incredible');
CALL copiar_aspiratne_artista(27,'The Incredible');
CALL copiar_aspiratne_artista(28,'The Incredible');
CALL copiar_aspiratne_artista(29,'The Incredible');
CALL copiar_aspiratne_artista(30,'The Incredible');
CALL copiar_aspiratne_artista(31,null);
CALL copiar_aspiratne_artista(32,'The Amazing');
CALL copiar_aspiratne_artista(33,'The Amazing');
CALL copiar_aspiratne_artista(34,'The Amazing');
CALL copiar_aspiratne_artista(35,'The Amazing');
CALL copiar_aspiratne_artista(36,'The Amazing');
CALL copiar_aspiratne_artista(37,'The Amazing');
CALL copiar_aspiratne_artista(38,'The Amazing');
CALL copiar_aspiratne_artista(39,'The Amazing');
CALL copiar_aspiratne_artista(40,'The Amazing');
CALL copiar_aspiratne_artista(41,'The Amazing');
CALL copiar_aspiratne_artista(42,'The Amazing');
CALL copiar_aspiratne_artista(43,'The Amazing');
CALL copiar_aspiratne_artista(44,'The Amazing');
CALL copiar_aspiratne_artista(45,'The Amazing');
CALL copiar_aspiratne_artista(46,'The Amazing');
CALL copiar_aspiratne_artista(47,'The Amazing');
CALL copiar_aspiratne_artista(48,'The Amazing');
CALL copiar_aspiratne_artista(49,'The Amazing');
CALL copiar_aspiratne_artista(50,'The Amazing');
CALL copiar_aspiratne_artista(51,'The Amazing');
CALL copiar_aspiratne_artista(52,'The Amazing');
CALL copiar_aspiratne_artista(53,'The Amazing');
CALL copiar_aspiratne_artista(54,'The Amazing');
CALL copiar_aspiratne_artista(55,'The Amazing');
CALL copiar_aspiratne_artista(56,'The Amazing');
CALL copiar_aspiratne_artista(57,'The Amazing');
CALL copiar_aspiratne_artista(58,'The Amazing');
CALL copiar_aspiratne_artista(59,'The Amazing');
CALL copiar_aspiratne_artista(60,'The Amazing');
CALL copiar_aspiratne_artista(61,'The Amazing');
CALL copiar_aspiratne_artista(62,'The Amazing');
CALL copiar_aspiratne_artista(63,'The Amazing');
CALL copiar_aspiratne_artista(64,'The Amazing');
CALL copiar_aspiratne_artista(65,'The Amazing');
CALL copiar_aspiratne_artista(66,'The Amazing');
CALL copiar_aspiratne_artista(67,null);
CALL copiar_aspiratne_artista(68,null);
CALL copiar_aspiratne_artista(69,null);
CALL copiar_aspiratne_artista(70,null);
CALL copiar_aspiratne_artista(71,null);
CALL copiar_aspiratne_artista(72,null);
CALL copiar_aspiratne_artista(73,null);
CALL copiar_aspiratne_artista(74,null);
CALL copiar_aspiratne_artista(75,null);
CALL copiar_aspiratne_artista(76,null);
CALL copiar_aspiratne_artista(77,null);
CALL copiar_aspiratne_artista(78,null);
CALL copiar_aspiratne_artista(79,'The New Wonder');
CALL copiar_aspiratne_artista(80,'The New Wonder');
CALL copiar_aspiratne_artista(81,'The New Wonder');
CALL copiar_aspiratne_artista(82,'The New Wonder');
CALL copiar_aspiratne_artista(83,'The New Wonder');
CALL copiar_aspiratne_artista(84,'The New Wonder');
CALL copiar_aspiratne_artista(85,'The New Wonder');
CALL copiar_aspiratne_artista(86,'The New Wonder');
CALL copiar_aspiratne_artista(87,'The New Wonder');
CALL copiar_aspiratne_artista(88,'The New Wonder');
CALL copiar_aspiratne_artista(89,'The New Wonder');
CALL copiar_aspiratne_artista(90,'The New Wonder');
CALL copiar_aspiratne_artista(91,'The New Wonder');
CALL copiar_aspiratne_artista(92,'The New Wonder');
CALL copiar_aspiratne_artista(93,'The New Wonder');
CALL copiar_aspiratne_artista(94,'The New Wonder');
CALL copiar_aspiratne_artista(95,'The New Wonder');
CALL copiar_aspiratne_artista(96,'The New Wonder');
CALL copiar_aspiratne_artista(97,'The New Wonder');
CALL copiar_aspiratne_artista(98,'The New Wonder');
CALL copiar_aspiratne_artista(99,'The New Wonder');
CALL copiar_aspiratne_artista(100,'The New Wonder');
CALL copiar_aspiratne_artista(101,'The New Wonder');
CALL copiar_aspiratne_artista(102,'The New Wonder');
CALL copiar_aspiratne_artista(103,'The New Wonder');
CALL copiar_aspiratne_artista(104,'The New Wonder');
CALL copiar_aspiratne_artista(105,'The New Wonder');
CALL copiar_aspiratne_artista(106,'The New Wonder');
CALL copiar_aspiratne_artista(107,'The New Wonder'); 
CALL copiar_aspiratne_artista(108,'The New Wonder');
CALL copiar_aspiratne_artista(109,'The New Wonder');
CALL copiar_aspiratne_artista(110,'The New Wonder');
CALL copiar_aspiratne_artista(111,'The New Wonder');
CALL copiar_aspiratne_artista(112,'The New Wonder');
CALL copiar_aspiratne_artista(113,'The New Wonder');
CALL copiar_aspiratne_artista(114,'The New Wonder');
CALL copiar_aspiratne_artista(115,'The New Wonder');
CALL copiar_aspiratne_artista(116,'The New Wonder');
CALL copiar_aspiratne_artista(117,'The New Wonder');
CALL copiar_aspiratne_artista(118,'The New Wonder');
CALL copiar_aspiratne_artista(119,'The New Wonder');
CALL copiar_aspiratne_artista(120,'The New Wonder');
CALL copiar_aspiratne_artista(121,null);
CALL copiar_aspiratne_artista(122,'The Improbable');
CALL copiar_aspiratne_artista(123,'The Improbable');
CALL copiar_aspiratne_artista(124,'The Improbable');
CALL copiar_aspiratne_artista(125,'The Improbable');
CALL copiar_aspiratne_artista(126,'The Improbable');
CALL copiar_aspiratne_artista(127,'The Improbable');
CALL copiar_aspiratne_artista(128,'The Improbable');
CALL copiar_aspiratne_artista(129,'The Improbable');
CALL copiar_aspiratne_artista(130,'The Improbable');
CALL copiar_aspiratne_artista(131,'The Improbable');
CALL copiar_aspiratne_artista(132,'The Improbable');
CALL copiar_aspiratne_artista(133,'The Improbable');
CALL copiar_aspiratne_artista(134,'The Improbable');
CALL copiar_aspiratne_artista(135,'The Improbable');
CALL copiar_aspiratne_artista(136,'The Improbable');
CALL copiar_aspiratne_artista(137,'The Improbable');
CALL copiar_aspiratne_artista(138,'The Improbable');
CALL copiar_aspiratne_artista(139,'The Improbable');
CALL copiar_aspiratne_artista(140,'The Improbable');
CALL copiar_aspiratne_artista(141,'The Improbable');
CALL copiar_aspiratne_artista(142,'The Improbable');
CALL copiar_aspiratne_artista(143,'The Improbable');
CALL copiar_aspiratne_artista(144,'The Improbable');
CALL copiar_aspiratne_artista(145,'The Improbable');
CALL copiar_aspiratne_artista(146,'The Improbable');
CALL copiar_aspiratne_artista(147,'The Improbable');
CALL copiar_aspiratne_artista(148,'The Improbable');
CALL copiar_aspiratne_artista(149,'The Improbable');
CALL copiar_aspiratne_artista(150,'The Improbable');
CALL copiar_aspiratne_artista(1150,null);
CALL copiar_aspiratne_artista(1151,null);
CALL copiar_aspiratne_artista(1152,null);
CALL copiar_aspiratne_artista(1153,null);
CALL copiar_aspiratne_artista(1154,null);
CALL copiar_aspiratne_artista(1155,null);
CALL copiar_aspiratne_artista(1156,null);
CALL copiar_aspiratne_artista(1157,null);
CALL copiar_aspiratne_artista(1158,null);
CALL copiar_aspiratne_artista(1159,null);
CALL copiar_aspiratne_artista(1160,null);
CALL copiar_aspiratne_artista(1161,null);
CALL copiar_aspiratne_artista(1162,null);
CALL copiar_aspiratne_artista(1163,null);
CALL copiar_aspiratne_artista(1164,null);
CALL copiar_aspiratne_artista(1165,null);
CALL copiar_aspiratne_artista(1166,null);
CALL copiar_aspiratne_artista(1167,null);
CALL copiar_aspiratne_artista(1168,null);
CALL copiar_aspiratne_artista(1169,null);
CALL copiar_aspiratne_artista(1170,null);
CALL copiar_aspiratne_artista(1171,null);
CALL copiar_aspiratne_artista(1172,null);
CALL copiar_aspiratne_artista(1173,null);
CALL copiar_aspiratne_artista(1174,null);
CALL copiar_aspiratne_artista(1175,null);
CALL copiar_aspiratne_artista(1176,null);
CALL copiar_aspiratne_artista(1177,null);
CALL copiar_aspiratne_artista(1178,null);
CALL copiar_aspiratne_artista(1179,null);
CALL copiar_aspiratne_artista(1180,null);
CALL copiar_aspiratne_artista(1181,null);
CALL copiar_aspiratne_artista(1182,null);
CALL copiar_aspiratne_artista(1183,null);
CALL copiar_aspiratne_artista(1184,null);
CALL copiar_aspiratne_artista(1185,null);
CALL copiar_aspiratne_artista(1186,null);
CALL copiar_aspiratne_artista(1187,null);
CALL copiar_aspiratne_artista(1188,null);
CALL copiar_aspiratne_artista(1189,null);
CALL copiar_aspiratne_artista(1190,null);
CALL copiar_aspiratne_artista(1191,'The Fast');
CALL copiar_aspiratne_artista(1192,'The Fast');
CALL copiar_aspiratne_artista(1193,'The Fast');
CALL copiar_aspiratne_artista(1194,'The Fast');
CALL copiar_aspiratne_artista(1195,'The Fast');
CALL copiar_aspiratne_artista(1196,'The Fast');
CALL copiar_aspiratne_artista(1197,'The Fast');
CALL copiar_aspiratne_artista(1198,'The Fast');
CALL copiar_aspiratne_artista(1199,'The Fast');
CALL copiar_aspiratne_artista(1200,'The Fast');
CALL copiar_aspiratne_artista(1201,'The Fast');
CALL copiar_aspiratne_artista(1202,'The Fast');
CALL copiar_aspiratne_artista(1203,'The Fast');
CALL copiar_aspiratne_artista(1204,'The Fast');
CALL copiar_aspiratne_artista(1205,'The Fast');
CALL copiar_aspiratne_artista(1206,'The Fast');
CALL copiar_aspiratne_artista(1207,'The Fast');
CALL copiar_aspiratne_artista(1208,'The Fast');
CALL copiar_aspiratne_artista(1209,'The Fast');
CALL copiar_aspiratne_artista(1210,'The Fast');
CALL copiar_aspiratne_artista(1211,'The Fast');
CALL copiar_aspiratne_artista(1212,'The Fast');
CALL copiar_aspiratne_artista(1213,'The Fast');
CALL copiar_aspiratne_artista(1214,'The Fast');
CALL copiar_aspiratne_artista(1215,'The Fast');
CALL copiar_aspiratne_artista(1216,'The Fast');
CALL copiar_aspiratne_artista(1217,'The Fast');
CALL copiar_aspiratne_artista(1218,null);
CALL copiar_aspiratne_artista(1219,'The Beauty');
CALL copiar_aspiratne_artista(1220,'The Beauty');
CALL copiar_aspiratne_artista(1221,'The Beauty');
CALL copiar_aspiratne_artista(1222,'The Beauty');
CALL copiar_aspiratne_artista(1223,'The Beauty');
CALL copiar_aspiratne_artista(1224,'The Beauty');
CALL copiar_aspiratne_artista(1225,'The Beauty');
CALL copiar_aspiratne_artista(1226,'The Beauty');
CALL copiar_aspiratne_artista(1227,'The Beauty');
CALL copiar_aspiratne_artista(1228,'The Beauty');
CALL copiar_aspiratne_artista(1229,'The Beauty');
CALL copiar_aspiratne_artista(1230,'The Beauty');
CALL copiar_aspiratne_artista(1231,'The Beauty');
CALL copiar_aspiratne_artista(1232,'The Beauty');
CALL copiar_aspiratne_artista(1233,'The Beauty');
CALL copiar_aspiratne_artista(1234,'The Beauty');
CALL copiar_aspiratne_artista(1235,'The Beauty');
CALL copiar_aspiratne_artista(1236,'The Beauty');
CALL copiar_aspiratne_artista(1237,'The Beauty');
CALL copiar_aspiratne_artista(1238,'The Beauty');
CALL copiar_aspiratne_artista(1239,'The Beauty');
CALL copiar_aspiratne_artista(1240,null);
CALL copiar_aspiratne_artista(1241,null);
CALL copiar_aspiratne_artista(1242,null);
CALL copiar_aspiratne_artista(1243,null);
CALL copiar_aspiratne_artista(1244,null);
CALL copiar_aspiratne_artista(1245,null);
